spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: ${DATABASE_DIALECT}
  profiles:
    active: ${CONFIG_PROFILES}
springdoc:
  swagger-ui:
    path: /swagger.html
logging:
  level:
    pfaron: DEBUG
  file:
    path: src/main/resources/log