version: "3.8"
services:
  petrol-stations-database:
    container_name: petrol-stations-database
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  petrol-stations-service:
    container_name: petrol-stations-service
    image: petrol-stations-service:0.1
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:root@petrol-stations-database:3306/petrol-stations?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=True
      DATABASE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    links:
      - petrol-stations-database
